# Generated by Django 5.0.6 on 2024-08-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_content_news_content_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='partners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='content_eng',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_eng',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='comment_eng',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='comment_ru',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='title_eng',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='title_ru',
            field=models.CharField(max_length=255),
        ),
    ]
