# Generated by Django 5.0.6 on 2024-08-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='answer',
            new_name='answer_uz',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='question',
            new_name='question_uz',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_eng',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_eng',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(default='', max_length=500),
        ),
    ]
