# Generated by Django 5.0.6 on 2024-08-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_answer_faq_answer_uz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='description',
            new_name='description_uz',
        ),
        migrations.AddField(
            model_name='statistics',
            name='description_eng',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='statistics',
            name='description_ru',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_eng',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_eng',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=500),
        ),
    ]
