# Generated by Django 5.0.6 on 2024-08-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_description_statistics_description_uz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='description',
            new_name='description_uz',
        ),
        migrations.AddField(
            model_name='partner',
            name='description_eng',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_ru',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='description_eng',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='description_ru',
            field=models.TextField(),
        ),
    ]
