# Generated by Django 5.0.6 on 2024-08-22 07:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_description_partner_description_uz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='technology',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='required_money',
            new_name='funding_goal',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='project_overview',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='startup_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='business_model',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='video',
        ),
        migrations.AddField(
            model_name='project',
            name='business_plan',
            field=models.FileField(default='', upload_to='business_plans/'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='elevator_pitch_video',
            field=models.FileField(default='', upload_to='elevator_pitch_videos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='financial_statements',
            field=models.FileField(default='', upload_to='financial_statements/'),
        ),
        migrations.AddField(
            model_name='project',
            name='how_it_works_video',
            field=models.FileField(default='', upload_to='how_it_works_videos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='other_documents',
            field=models.FileField(default='', upload_to='other_documents/'),
        ),
        migrations.AddField(
            model_name='project',
            name='pitchdeck',
            field=models.FileField(default='', upload_to='pitchdecks/'),
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.CharField(default='Tashkent', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='social_media_links',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='tagline',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='use_of_funds',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='website_url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description_eng',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description_ru',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('legal_name', models.CharField(max_length=255)),
                ('TIN', models.CharField(max_length=12)),
                ('date_of_registration', models.DateField()),
                ('national_classifier_of_activities', models.CharField(max_length=255)),
                ('legal_address', models.CharField(max_length=500)),
                ('name_of_director', models.CharField(max_length=255)),
                ('director_TIN', models.CharField(max_length=12)),
                ('share_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('state_of_activity', models.CharField(max_length=255)),
                ('number_of_employees', models.PositiveIntegerField()),
                ('name_of_bank', models.CharField(max_length=255)),
                ('MFO', models.CharField(max_length=20)),
                ('account_number_1', models.CharField(max_length=50)),
                ('account_number_2', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_phone_number_1', models.CharField(max_length=15)),
                ('contact_phone_number_2', models.CharField(blank=True, max_length=15, null=True)),
                ('accountant_phone_number', models.CharField(max_length=15)),
                ('international_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('legal_address_of_company', models.CharField(max_length=500)),
                ('physical_address_of_company', models.CharField(max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('linkedin_profile', models.URLField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='app.category')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subcategory'),
        ),
    ]
