# Generated by Django 5.0.6 on 2024-08-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_category_rename_category_project_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
    ]
