# Generated by Django 5.0.6 on 2024-08-22 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_project_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='business_plan',
            field=models.FileField(upload_to='business_plans/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='app.company'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='elevator_pitch_video',
            field=models.FileField(upload_to='elevator_pitch_videos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='financial_statements',
            field=models.FileField(upload_to='financial_statements/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='how_it_works_video',
            field=models.FileField(upload_to='how_it_works_videos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='other_documents',
            field=models.FileField(upload_to='other_documents/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pitchdeck',
            field=models.FileField(upload_to='pitchdecks/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='tagline',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='use_of_funds',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='website_url',
            field=models.URLField(max_length=255),
        ),
    ]
