# Generated by Django 5.0.6 on 2024-08-24 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_bank_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankmember',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='created_bank_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CouncilMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed')], default='upcoming', max_length=50)),
                ('selected_applications', models.ManyToManyField(related_name='meetings', to='app.application')),
                ('selected_members', models.ManyToManyField(related_name='meetings', to='app.bankmember')),
            ],
        ),
    ]
