# Generated by Django 5.0.6 on 2024-08-29 06:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_criteria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='account_number_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_phone_number_2',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='company',
            name='international_contact_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='TemporaryCompanyData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step1_data', models.JSONField(blank=True, null=True)),
                ('step2_data', models.JSONField(blank=True, null=True)),
                ('step3_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
