# Generated by Django 5.0.6 on 2024-08-29 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_company_account_number_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarycompanydata',
            name='id',
            field=models.CharField(default='<function uuid4 at 0x0000027FF952C540>', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='temporarycompanydata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
