# Generated by Django 5.0.6 on 2024-08-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_temporarycompanydata_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='MFO',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='TIN',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='account_number_1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='account_number_2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='director_TIN',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='share_capital',
            field=models.DecimalField(decimal_places=2, max_digits=255),
        ),
        migrations.DeleteModel(
            name='TemporaryCompanyData',
        ),
    ]
