# Generated by Django 5.0.6 on 2024-08-30 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_project_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='founder',
            name='linkedin_profile',
            field=models.URLField(default='linkedin', max_length=255),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pitchdeck_sections', to='app.project'),
        ),
    ]
