# Generated by Django 5.0.6 on 2024-09-05 05:29

import app.models.projects
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_founder_bio_alter_founder_linkedin_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.projects.project_images_file_path),
        ),
    ]
