# Generated by Django 5.0.6 on 2024-09-05 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_project_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationscore',
            name='criteria',
        ),
        migrations.AddField(
            model_name='applicationscore',
            name='criteria_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.criteria'),
        ),
    ]
