# Generated by Django 5.0.6 on 2024-09-05 12:13

import app.models.company
import app.models.investor
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_applicationscore_criteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.company.company_logos_file_path),
        ),
        migrations.AlterField(
            model_name='investordocument',
            name='file',
            field=models.FileField(upload_to=app.models.investor.investor_documents_file_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to=app.models.investor.invoices_file_path),
        ),
    ]
