# Generated by Django 5.0.6 on 2024-09-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_project_deadline_project_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='funding_goal',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
