# Generated by Django 5.0.6 on 2024-09-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_project_min_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalhistory',
            name='date_of_action',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='approvalhistory',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
