# Generated by Django 5.0.6 on 2024-09-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_score_criteria_name_score_criteria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
