# Generated by Django 5.0.6 on 2024-09-09 13:13

import app.models.aboutus
import app.models.investor
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_sendquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_eng', models.CharField(max_length=255)),
                ('description_uz', models.TextField()),
                ('description_uz_ru', models.TextField()),
                ('description_uz_eng', models.TextField()),
                ('image', models.ImageField(upload_to=app.models.aboutus.about_us_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField()),
                ('cardId', models.CharField(max_length=150)),
                ('owner', models.CharField(max_length=100)),
                ('card_name', models.CharField(blank=True, max_length=100, null=True)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expiration_date', models.CharField()),
                ('bankid', models.IntegerField()),
                ('vendor', models.CharField(max_length=100)),
                ('processing', models.CharField(max_length=100)),
                ('phone_number', models.CharField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_main', models.BooleanField(default=False)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_cards', to='app.investor')),
            ],
        ),
        migrations.CreateModel(
            name='CardImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to=app.models.investor.card_image_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payed_date', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.investor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('CRD', 'Created'), ('NPD', 'Not Paid'), ('PD', 'Paid'), ('CLD', 'Cancelled'), ('EXP', 'Expired')], default='NPD', max_length=3)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.investor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.project')),
            ],
        ),
        migrations.RemoveField(
            model_name='bankcard',
            name='investor',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='invoice_file',
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor', to='app.investor'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='app.project'),
        ),
        migrations.AddField(
            model_name='card',
            name='background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cardimages'),
        ),
        migrations.AddField(
            model_name='check',
            name='invoice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.invoice'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.invoice'),
        ),
        migrations.DeleteModel(
            name='BankCard',
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('investor',), name='unique_is_main_per_user'),
        ),
    ]
