# Generated by Django 5.0.6 on 2024-09-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_aboutus_card_cardimages_check_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='social_media_links',
        ),
        migrations.AddField(
            model_name='project',
            name='linkedin',
            field=models.URLField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('returned_for_revision', 'Returned for Revision'), ('approved_by_moderator', 'Approved by Moderator'), ('approved_by_bank_secretary', 'Approved by Bank Secretary'), ('rejected', 'Rejected'), ('visible', 'Visible to Users')], default='created', max_length=50),
        ),
        migrations.DeleteModel(
            name='ApplicationApproval',
        ),
    ]
