# Generated by Django 5.0.6 on 2024-09-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_project_social_media_links_project_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='linkedin',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
