# Generated by Django 5.0.6 on 2024-09-11 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_investor_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fixed_price', 'Fixed Price'), ('percentage', 'Percentage')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('investor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.investor')),
            ],
        ),
        migrations.CreateModel(
            name='ClubBankAccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=34)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('routing_number', models.CharField(blank=True, max_length=9, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='app.club')),
            ],
        ),
    ]
