# Generated by Django 5.0.6 on 2024-09-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_club_clubbankaccountinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
