# Generated by Django 5.0.6 on 2024-09-11 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_club_fixed_price_club_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_club', to='app.investor'),
        ),
        migrations.AddField(
            model_name='club',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='check',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_check', to='app.project'),
        ),
        migrations.AlterField(
            model_name='club',
            name='investor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_owner', to='app.investor'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_invoice', to='app.investor'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_investor_invoice', to='app.project'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_transaction', to='app.investor'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_investor', to='app.project'),
        ),
        migrations.CreateModel(
            name='ClubInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('CRD', 'Created'), ('NPD', 'Not Paid'), ('PD', 'Paid'), ('CLD', 'Cancelled'), ('EXP', 'Expired')], default='NPD', max_length=3)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_invoice', to='app.club')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_club_invoice', to='app.investor')),
            ],
        ),
        migrations.CreateModel(
            name='ClubCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('payed_date', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_check', to='app.club')),
                ('investor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.investor')),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clubinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='ClubTransactionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('account_number', models.CharField(default='', max_length=16)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club', to='app.club')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.invoice')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_transaction_projects', to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorTransactionClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('card_number', models.CharField(default='', max_length=16)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_transaction_club', to='app.club')),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_club', to='app.investor')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.clubinvoice')),
            ],
        ),
    ]
