# Generated by Django 5.0.6 on 2024-09-11 12:32

import app.models.club
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_club_members_club_name_alter_check_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=app.models.club.club_file_path),
        ),
    ]
