# Generated by Django 5.0.6 on 2024-09-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_club_created_at_club_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clubbankaccountinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clubbankaccountinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
