# Generated by Django 5.0.6 on 2024-09-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_alter_club_created_at_alter_club_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitchdecksection',
            name='project',
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='business_model_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='business_model_description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='business_model_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='business_model_name_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='competitors_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='competitors_description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='competitors_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='competitors_name_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='financial_acquisitions_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='financial_acquisitions_description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='financial_acquisitions_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='financial_acquisitions_name_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='how_it_works_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='how_it_works_description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='how_it_works_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='how_it_works_name_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='market_size_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='market_size_description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='market_size_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='market_size_name_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='problem_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='problem_description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='problem_name_eng',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='problem_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='problem_name_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='solution_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='solution_description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='solution_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='solution_name_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='special_sauce_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='special_sauce_description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='special_sauce_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='special_sauce_name_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='target_customer_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='target_customer_description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='target_customer_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='target_customer_name_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='team_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='team_description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='team_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='team_name_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='technology_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='technology_description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='technology_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='technology_name_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='tractions_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='tractions_description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='tractions_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='tractions_name_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='why_now_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='why_now_description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='why_now_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitchdecksection',
            name='why_now_name_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
