# Generated by Django 5.0.6 on 2024-09-12 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_remove_pitchdecksection_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchdecksection',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pitch_decks', to='app.project'),
        ),
    ]
