# Generated by Django 5.0.6 on 2024-09-12 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_pitchdecksection_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchdecksection',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pitchdeck_sections', to='app.project'),
        ),
    ]
