# Generated by Django 5.0.6 on 2024-09-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_requestetojoinclub'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='card',
            name='unique_is_main_per_user',
        ),
    ]
