# Generated by Django 5.0.6 on 2024-09-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_remove_card_unique_is_main_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaisingContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=50)),
            ],
        ),
    ]
