# Generated by Django 5.0.6 on 2024-09-12 11:53

import app.models.blog
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_raisingcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=app.models.blog.blog_images_file_path)),
                ('content', models.TextField()),
                ('writer_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('writer_profile_photo', models.ImageField(blank=True, null=True, upload_to=app.models.blog.writer_photos_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
