# Generated by Django 5.0.6 on 2024-09-12 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_club_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_check', to='app.club'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_invoice', to='app.club'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_transaction', to='app.club'),
        ),
        migrations.AlterField(
            model_name='check',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.investor'),
        ),
        migrations.AlterField(
            model_name='clubcheck',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_investor_check', to='app.club'),
        ),
        migrations.AlterField(
            model_name='clubinvoice',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_investor_invoice', to='app.club'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_invoice', to='app.investor'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_transaction', to='app.investor'),
        ),
    ]
