# Generated by Django 5.0.6 on 2024-09-12 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_check_club_invoice_club_transaction_club_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_club', to='app.club'),
        ),
        migrations.AlterField(
            model_name='check',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_project', to='app.project'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_club', to='app.club'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_investor', to='app.investor'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_club', to='app.club'),
        ),
    ]
