# Generated by Django 5.0.6 on 2024-09-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_alter_check_club_alter_check_project_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClubTransactionProject',
        ),
    ]
