# Generated by Django 5.0.6 on 2024-09-14 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_project_equity_alter_partner_logo_projectinvestment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=500)),
                ('description_uz', models.TextField()),
                ('name_ru', models.CharField(max_length=500)),
                ('description_ru', models.TextField()),
                ('name_eng', models.CharField(max_length=500)),
                ('description_eng', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='equity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='GlossarySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=500)),
                ('description_uz', models.TextField()),
                ('name_ru', models.CharField(max_length=500)),
                ('description_ru', models.TextField()),
                ('name_eng', models.CharField(max_length=500)),
                ('description_eng', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.glossary')),
            ],
        ),
    ]
