# Generated by Django 5.0.6 on 2024-09-18 05:30

import app.models.glossary
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_glossary_alter_project_equity_glossarysection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glossarysection',
            old_name='section',
            new_name='glossary',
        ),
        migrations.AddField(
            model_name='glossary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.glossary.glossary_image_path),
        ),
        migrations.AddField(
            model_name='glossarysection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.glossary.glossary_section_image_path),
        ),
    ]
