# Generated by Django 5.0.6 on 2024-09-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_rename_section_glossarysection_glossary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossary',
            name='category',
            field=models.CharField(choices=[('startup_ecosystem', 'Startup Ecosystem'), ('funding_investment', 'Funding and Investment'), ('technology_innovation', 'Technology and Innovation'), ('business_models', 'Business Models'), ('entrepreneurship', 'Entrepreneurship'), ('market_growth', 'Market and Growth')], default='', max_length=50),
        ),
    ]
