# Generated by Django 5.0.6 on 2024-09-20 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_rename_business_model_description_eng_pitchdecksection_business_model_description_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glossary',
            old_name='description_eng',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='glossary',
            old_name='name_eng',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='glossarysection',
            old_name='description_eng',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='glossarysection',
            old_name='name_eng',
            new_name='name_en',
        ),
    ]
