# Generated by Django 5.0.6 on 2024-09-21 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_rename_description_eng_glossary_description_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('total_investments', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_portfolio_companies', models.IntegerField(default=0)),
                ('total_investments_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('last_investment_date', models.DateField(blank=True, null=True)),
                ('sectors', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment_company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
