# Generated by Django 5.0.6 on 2024-09-27 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_investmentcompany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentcompany',
            old_name='last_investment_date',
            new_name='date_founded',
        ),
        migrations.RenameField(
            model_name='investmentcompany',
            old_name='total_portfolio_companies',
            new_name='number_of_exits',
        ),
        migrations.RemoveField(
            model_name='investmentcompany',
            name='total_investments_amount',
        ),
        migrations.AddField(
            model_name='investmentcompany',
            name='headquarters',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentcompany',
            name='number_of_portfolio_organizations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investmentcompany',
            name='total_portfolio_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='investmentcompany',
            name='total_investments',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PortfolioCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('date_founded', models.DateField(blank=True, null=True)),
                ('investment_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_companies', to='app.investmentcompany')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('seed', 'Seed Stage'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('growth', 'Growth Stage'), ('late', 'Late Stage')], default='seed', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('investment_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='app.investmentcompany')),
                ('portfolio_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='app.portfoliocompany')),
            ],
        ),
    ]
