# Generated by Django 5.0.6 on 2024-09-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_rename_last_investment_date_investmentcompany_date_founded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='investment_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='stage',
            field=models.CharField(choices=[('seed', 'Seed Stage'), ('bridge', 'Bridge Stage'), ('undisclosed', 'Undisclosed'), ('growth', 'Growth Stage'), ('late', 'Late Stage')], default='seed', max_length=20),
        ),
    ]
