# Generated by Django 5.0.6 on 2024-09-27 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_companyinfo_acquisition_companyinvestment_financials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acquisitions', to='app.companyinfo'),
        ),
        migrations.AlterField(
            model_name='companyinvestment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='app.companyinfo'),
        ),
        migrations.AlterField(
            model_name='financials',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='app.companyinfo'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funding_rounds', to='app.companyinfo'),
        ),
        migrations.AlterField(
            model_name='story',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='app.companyinfo'),
        ),
    ]
