# Generated by Django 5.0.6 on 2024-08-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_otp_counter_customuser_otp_sent_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
