# Generated by Django 5.0.6 on 2024-08-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_temporaryuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_counter', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='TemporaryUser',
        ),
    ]
