# Generated by Django 5.0.6 on 2024-08-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_uniqueconfig_delete_temporaryuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('regular', 'Regular User'), ('startup_owner', 'Startup Owner'), ('investor', 'Investor'), ('bank', 'Bank')], default='regular', max_length=50),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
