# Generated by Django 5.0.6 on 2024-08-20 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userdevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdevice',
            name='device_name',
        ),
        migrations.AddField(
            model_name='userdevice',
            name='can_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='login_attempt_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone_number', 'Phone Number')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
