# Generated by Django 5.0.6 on 2024-08-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_userdevice_device_name_userdevice_can_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone_number', 'Phone Number')], max_length=12),
        ),
    ]
