# Generated by Django 5.0.6 on 2024-08-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_userdevice_login_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('regular', 'Regular User'), ('company', 'Company'), ('investor', 'Investor'), ('bank_staff', 'Bank Staff'), ('bank_council', 'Bank Council')], max_length=50, unique=True),
        ),
    ]
