# Generated by Django 5.0.6 on 2024-08-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_customuser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('regular', 'Regular User'), ('company', 'Company'), ('investor', 'Investor'), ('bank_secretary', 'Bank Secretary'), ('bank_council', 'Bank Council')], max_length=50, unique=True),
        ),
    ]
