# Generated by Django 5.0.6 on 2024-09-11 12:32

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=user.models.avatar_file_path),
        ),
        migrations.AddField(
            model_name='customuser',
            name='caunty',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deposite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
