# Generated by Django 5.0.6 on 2024-09-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_customuser_avatar_customuser_caunty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('company', 'Company'), ('investor', 'Investor'), ('investing_company', 'Investing Company'), ('moderator', 'Moderator'), ('bank_secretary', 'Bank Secretary'), ('bank_council', 'Bank Council')], max_length=50, unique=True),
        ),
    ]
